### PR TITLE
made the mod clientside only

### PR DESCRIPTION
**Pull request by loordgek**
do not know whether this will break the api
but this will make checking if mods can use NotEnoughKeys, easy  
you only need to check for "isModLoaded" if it isn't 
1 the mod is not loaded 
2 it is running on a server

### CODE REVIEW

**Comment by TheTemportalist** [comment]
This is a reason why we added these in the first place. It is not right just to crash the server. You should look at the history before suggesting things like this.

**Comment by loordgek** [comment]
can you point me to it?

**Comment by TheTemportalist** [comment]
@dmodoomsirius

**Comment by dmodoomsirius** [comment]
We were looking for a way for the server to say im a client only mod skip me. also because people were putting NEK on the server.

**Comment by loordgek** [comment]
@dmodoomsirius this is telling forge to skip it on the server

**Comment by TheTemportalist** [comment]
It should be noted that loordgeek added an "acceptedMinecraftVersions" line, which indicates 1.8, while I still push 1.7.10 code/releases

**Comment by dmodoomsirius** [comment]
@TheTemportalist the pr is into the 1.8 branch

**Comment by loordgek** [comment]
but this 1.8 so ??

**Comment by dmodoomsirius** [comment]
I can port this back to 1.7.10.

**Comment by loordgek** [comment]
no this got added is 1.8
http://www.minecraftforge.net/forum/index.php/topic,31020.0.html
@Mode Side Control:
New @Mod properties to define which environment to load the mod on.
   clientSideOnly will only be loaded in the Client environment.
   serverSideOnly will only be loaded in the Dedicated server environment.
   Combine with acceptedMinecraftVersions to prevent users from loading the mod in the incorrect environment.
   For the love of god modders USE THIS! It'll stop all those 'you ran a 1.7 mod on 1.8!' and 'you ran a client mod on the server!'

**Comment by dmodoomsirius** [comment]
I really should check the scripts to see what forge version for 1.8 NEK compiles against.

**Comment by loordgek** [comment]
version.forge=11.14.3.1450

**Comment by GirafiStudios** [comment]
https://github.com/mod-warriors/NotEnoughKeys/commit/762a814e2fb0d0c0142718e9b0d58e170601b9fc

**Pull request closed without merging**
